In [1]:
import pandas as pd
df = pd.read_excel("LOANS DATA 2019 TO 2025 - FINAL DATASET UNCLEAN.xlsx")
pd.set_option('display.max_columns', None)
df

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.00,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,4.900000e+07,0.000000e+00,7.000000e+06,0.00,7.000000e+06
1,2019,12,BORROWER_100,BORROWER_100-2019-12,ILAGAN LENDING CENTER,NCLLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Micro,No Program,Isabela,Cagayan Valley,Loss,18.00,Fixed,TERM LOAN,Secured,REAL ESTATE,DBP,Short Term,366,1999-05-21,PDO,NPA,4.441965e+05,4.441965e+05,4.441965e+05,444196.54,4.441965e+05
2,2019,12,BORROWER_1002,BORROWER_1002-2019-12,BACOLOD LENDING CENTER,VLG,CONSTRUCTION,MED - SME Loans - Medium Scale Enterprise,Medium,Infrastructure Contractor Support Program,Negros Occidental,Western Visayas,Current,6.50,Variable,REVOLVING CREDIT LINE,Secured,MACHINERY & EQUIPMENT,DBP,Short Term,177,NaT,CUR,PA,7.800000e+07,1.313600e+07,9.000000e+06,108047.49,9.000000e+06
3,2019,12,BORROWER_1003,BORROWER_1003-2019-12,ILOILO LENDING CENTER,VLG,EDUCATION,LPN - Loans to Private Corp. - Non Financial,Large,RESPONSE - ESKWELA,ILOILO,Western Visayas,Specially Mentioned,6.00,Fixed,TERM LOAN,Secured,MACHINERY & EQUIPMENT,DBP,Long Term,3287,NaT,CUR,PA,1.000000e+08,1.402238e+08,1.000000e+08,0.00,1.000000e+08
4,2019,12,BORROWER_1004,BORROWER_1004-2019-12,MIDDLE MARKET II DEPT.,SMERMMLG,CONSTRUCTION,LPN - Loans to Private Corp. - Non Financial,Large,No Program,Rizal,Calabarzon,Current,5.25,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,90,NaT,CUR,PA,1.475000e+09,1.750000e+08,1.320000e+08,0.00,1.320000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52580,2025,3,BORROWER_986,BORROWER_986-2025-3,BUTUAN LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Medium,Assistance for Economic and Social Development...,Agusan del Sur,Caraga,Pass,8.44,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,4383,NaT,CUR,PA,3.994195e+08,0.000000e+00,1.549172e+08,0.00,8.878966e+07
52581,2025,3,BORROWER_992,BORROWER_992-2025-3,ZAMBOANGA LENDING CENTER,SWMLG,HUMAN HEALTH AND SOCIAL WORK ACTIVITIES,LPN - Loans to Private Corp. - Non Financial,Large,Strategic Healthcare Investments for Enhanced ...,ZAMBOANGA DEL SUR,Zamboanga Peninsula,Pass,8.30,Variable,REVOLVING CREDIT LINE,Secured,REM - RESIDENTIAL,DBP,Long Term,176,NaT,CUR,PA,4.333884e+08,1.364924e+09,2.025161e+08,0.00,1.532790e+08
52582,2025,3,BORROWER_995,BORROWER_995-2025-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Loss,7.00,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,88,2019-03-01,PDO,NPA,1.000000e+06,0.000000e+00,1.000000e+06,1000000.00,1.000000e+06
52583,2025,3,BORROWER_996,BORROWER_996-2025-3,CAGAYAN DE ORO LENDING CENTER,NMLG,HUMAN HEALTH AND SOCIAL WORK ACTIVITIES,LPN - Loans to Private Corp. - Non Financial,Large,Strategic Healthcare Investments for Enhanced ...,MISAMIS ORIENTAL,Northern Mindanao,SUBSTANDARD PARTIALLY SECURED/UNSECURED,9.30,Variable,TERM LOAN,Secured,REAL ESTATE,DBP,Long Term,178,2021-01-12,PDO,NPA,3.323333e+08,1.729828e+08,9.833333e+07,23449451.67,9.833333e+07
52584,2025,3,BORROWER_998,BORROWER_998-2025-3,TACLOBAN LENDING CENTER,VLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Large,No Program,LEYTE,Eastern Visayas,Pass,7.60,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,4444,NaT,CUR,PA,2.154570e+07,0.000000e+00,2.154570e+07,0.00,1.316682e+07

In [2]:
df.shape

(52585, 29)

1. Replacing Null Values

In [4]:
#check null values
df.isnull().sum()

YEAR                                   0
MONTH_ID                               0
BORROWER_CODE_NAME                     0
JOINT                                  0
LENDING UNIT                           0
LG                                     0
Major Industry                         0
Account/Loan Type                      0
Customer Size                          0
Development Lending Program            0
Location                               0
Region                                 0
Account Class                        335
Interest Rate                          0
Interest Type                         10
Type of Facility                       0
Collateral Type                        0
Collateral Type Description            0
Source                                 0
Loan Term                              0
No. of Days-Loan Term                  0
Past Due Date                      42745
Loan Status                            0
Area Code                              0
Sum of Sum of Approved Amount          0
Sum of Sum of Collateral Amount        0
Sum of Sum of Release Amount           0
Sum of Sum of Booked Reserves          0
Sum of Sum of Loan Portfolio           0
dtype: int64

In [5]:
df2 = df.sort_values(by=['BORROWER_CODE_NAME','YEAR','MONTH_ID'],ascending=[True,True,False])
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50

In [6]:
df2.isnull().sum()

YEAR                                   0
MONTH_ID                               0
BORROWER_CODE_NAME                     0
JOINT                                  0
LENDING UNIT                           0
LG                                     0
Major Industry                         0
Account/Loan Type                      0
Customer Size                          0
Development Lending Program            0
Location                               0
Region                                 0
Account Class                        335
Interest Rate                          0
Interest Type                         10
Type of Facility                       0
Collateral Type                        0
Collateral Type Description            0
Source                                 0
Loan Term                              0
No. of Days-Loan Term                  0
Past Due Date                      42745
Loan Status                            0
Area Code                              0
Sum of Sum of Approved Amount          0
Sum of Sum of Collateral Amount        0
Sum of Sum of Release Amount           0
Sum of Sum of Booked Reserves          0
Sum of Sum of Loan Portfolio           0
dtype: int64

In [7]:
df2[df2['Account Class'].isna()]

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio
12,2019,12,BORROWER_1013,BORROWER_1013-2019-12,NAGA LENDING CENTER,SLLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Medium,Assistance for Economic and Social Development...,CAMARINES NORTE,Bicol,NaN,5.250,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2205,NaT,CUR,PA,1.369775e+09,0.0,51126000.00,0.0,35371196.95
2382,2020,3,BORROWER_1013,BORROWER_1013-2020-3,NAGA LENDING CENTER,SLLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Medium,Assistance for Economic and Social Development...,CAMARINES NORTE,Bicol,NaN,5.250,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2205,NaT,CUR,PA,1.369775e+09,0.0,51126000.00,0.0,33276453.58
9543,2020,12,BORROWER_1106,BORROWER_1106-2020-12,BUTUAN LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Large,Connecting Rural Urban Intermodal Systems Effi...,SURIGAO DEL SUR,Caraga,NaN,6.000,Fixed,TERM LOAN,Secured,MACHINERY & EQUIPMENT,JICA,Long Term,3653,NaT,CUR,PA,7.253370e+07,72371000.0,72533700.00,0.0,34252025.00
19254,2021,12,BORROWER_1106,BORROWER_1106-2021-12,BUTUAN LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Large,Connecting Rural Urban Intermodal Systems Effi...,SURIGAO DEL SUR,Caraga,NaN,6.000,Fixed,TERM LOAN,Secured,MACHINERY & EQUIPMENT,JICA,Long Term,3653,NaT,CUR,PA,7.253370e+07,72371000.0,72533700.00,0.0,24177900.00
16815,2021,9,BORROWER_1106,BORROWER_1106-2021-9,BUTUAN LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Large,Connecting Rural Urban Intermodal Systems Effi...,SURIGAO DEL SUR,Caraga,NaN,6.000,Fixed,TERM LOAN,Secured,MACHINERY & EQUIPMENT,JICA,Long Term,3653,NaT,CUR,PA,7.253370e+07,72371000.0,72533700.00,0.0,26192725.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21677,2021,12,BORROWER_999,BORROWER_999-2021-12,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,NaN,5.895,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,5.397300e+07,0.0,42877607.16,0.0,23387785.76
19179,2021,9,BORROWER_999,BORROWER_999-2021-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,NaN,5.895,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,5.397300e+07,0.0,42877607.16,0.0,25336767.90
16736,2021,6,BORROWER_999,BORROWER_999-2021-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,NaN,5.895,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,5.397300e+07,0.0,42877607.16,0.0,27285750.04
14315,2021,3,BORROWER_999,BORROWER_999-2021-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,NaN,5.895,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,5.397300e+07,0.0,42877607.16,0.0,29234732.18
24151,2022,3,BORROWER_999,BORROWER_999-2022-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,NaN,5.895,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,5.397300e+07,0.0,42877607.16,0.0,21438803.62

In [8]:
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50

In [9]:
df2.isnull().sum()

YEAR                                   0
MONTH_ID                               0
BORROWER_CODE_NAME                     0
JOINT                                  0
LENDING UNIT                           0
LG                                     0
Major Industry                         0
Account/Loan Type                      0
Customer Size                          0
Development Lending Program            0
Location                               0
Region                                 0
Account Class                        335
Interest Rate                          0
Interest Type                         10
Type of Facility                       0
Collateral Type                        0
Collateral Type Description            0
Source                                 0
Loan Term                              0
No. of Days-Loan Term                  0
Past Due Date                      42745
Loan Status                            0
Area Code                              0
Sum of Sum of Approved Amount          0
Sum of Sum of Collateral Amount        0
Sum of Sum of Release Amount           0
Sum of Sum of Booked Reserves          0
Sum of Sum of Loan Portfolio           0
dtype: int64

In [10]:
df2['Account Class'] = df2['Account Class'].fillna(method="bfill")
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50

In [11]:
df2.isnull().sum()

YEAR                                   0
MONTH_ID                               0
BORROWER_CODE_NAME                     0
JOINT                                  0
LENDING UNIT                           0
LG                                     0
Major Industry                         0
Account/Loan Type                      0
Customer Size                          0
Development Lending Program            0
Location                               0
Region                                 0
Account Class                          0
Interest Rate                          0
Interest Type                         10
Type of Facility                       0
Collateral Type                        0
Collateral Type Description            0
Source                                 0
Loan Term                              0
No. of Days-Loan Term                  0
Past Due Date                      42745
Loan Status                            0
Area Code                              0
Sum of Sum of Approved Amount          0
Sum of Sum of Collateral Amount        0
Sum of Sum of Release Amount           0
Sum of Sum of Booked Reserves          0
Sum of Sum of Loan Portfolio           0
dtype: int64

In [12]:
df2['Interest Type'] = df2['Interest Type'].fillna(method="bfill")
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50

In [13]:
df2.isnull().sum()

YEAR                                   0
MONTH_ID                               0
BORROWER_CODE_NAME                     0
JOINT                                  0
LENDING UNIT                           0
LG                                     0
Major Industry                         0
Account/Loan Type                      0
Customer Size                          0
Development Lending Program            0
Location                               0
Region                                 0
Account Class                          0
Interest Rate                          0
Interest Type                          0
Type of Facility                       0
Collateral Type                        0
Collateral Type Description            0
Source                                 0
Loan Term                              0
No. of Days-Loan Term                  0
Past Due Date                      42745
Loan Status                            0
Area Code                              0
Sum of Sum of Approved Amount          0
Sum of Sum of Collateral Amount        0
Sum of Sum of Release Amount           0
Sum of Sum of Booked Reserves          0
Sum of Sum of Loan Portfolio           0
dtype: int64

2. Adding New Feature

In [15]:
def month_name(month_id):
    if month_id == 3:
        return 'MAR'
    if month_id == 6:
        return 'JUN'
    if month_id == 9:
        return 'SEPT'
    if month_id == 12:
        return 'DEC'

df2['Month Name'] = df2['MONTH_ID'].map(month_name)
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio,Month Name
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00,DEC
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,DEC
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,SEPT
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00,JUN
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00,MAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92,JUN
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06,MAR
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22,SEPT
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36,JUN
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50,MAR

In [16]:
def interest_rate_range(interest_rate):
    if interest_rate < 1.00:
        return 'Below 1.00%'
    if 1.00 <= interest_rate < 2.99:
        return '1.00% - 2.99%'
    if 3.00 <= interest_rate < 4.99:
        return '3.00% - 4.99%'  
    if 5.00 <= interest_rate < 7.99:
        return '5.00% - 7.99%'  
    if 8.00 <= interest_rate < 9.99:
        return '8.00% - 9.99%'  
    if 10.00 <= interest_rate < 11.99:
        return '10.00% - 11.99%'  
    if 12.00 <= interest_rate < 14.99:
        return '12.00% - 14.99%'  
    if 15.00 <= interest_rate < 19.99:
        return '15.00% - 19.99%'  
    if interest_rate > 20.00:
        return '1.00% - 2.99%'  

df2['Interest Rate Range'] = df2['Interest Rate'].map(interest_rate_range)
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio,Month Name,Interest Rate Range
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00,DEC,10.00% - 11.99%
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,DEC,8.00% - 9.99%
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,SEPT,8.00% - 9.99%
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00,JUN,10.00% - 11.99%
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,Current,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00,MAR,10.00% - 11.99%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92,JUN,5.00% - 7.99%
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06,MAR,5.00% - 7.99%
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22,SEPT,5.00% - 7.99%
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36,JUN,5.00% - 7.99%
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,Pass,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50,MAR,5.00% - 7.99%

3. Capitalization

In [18]:
df2['Location'] = df2['Location'].str.upper()
df2['Account Class'] = df2['Account Class'].str.upper()
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio,Month Name,Interest Rate Range
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00,DEC,10.00% - 11.99%
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,DEC,8.00% - 9.99%
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,SEPT,8.00% - 9.99%
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00,JUN,10.00% - 11.99%
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SMA - SME Loans - Small Scale Enterprise,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00,MAR,10.00% - 11.99%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92,JUN,5.00% - 7.99%
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06,MAR,5.00% - 7.99%
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22,SEPT,5.00% - 7.99%
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36,JUN,5.00% - 7.99%
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,LLG - Loans to Local Gov't Unit,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50,MAR,5.00% - 7.99%

4. Replacing Values

In [20]:
df2['Account/Loan Type'] = df2['Account/Loan Type'].replace({"'": "", '"': ""}, regex=True)

In [21]:
AccType_grouped = df2.groupby('Account/Loan Type')['Sum of Sum of Loan Portfolio'].count()
AccType_grouped

Account/Loan Type
AGRICULTURAL LOANS -AGRA                            77
AGRICULTURAL LOANS -AGRI                           752
AIC - Agrarian Reform & Other Agri Loans - AI       22
BA - Loans to Priv Corp - Non Fin CL BA O/S         22
CLT - Loans to Priv Corp -Non Fin CL under TR       95
GLC - Loans to LGU - Cust Liab under TR             13
GNF - Loans to GOCC Non-Financial                 1183
IBK - Interbank Term Loans Recble - KB/UKB          12
IBO - Interbank Term Loans Recble - Oth Banks        9
IHP - Loans to Indl for Housing Purposes           437
INB - Interbank Term Loans Recble - NBQB             1
LLG - Loans to Local Govt Unit                    8729
LNG - Loans to National Govt                        42
LPF - Loans to Private Corp. - Financial           437
LPN - Loans to Private Corp. - Non Financial     12867
MEB - SME Loans - Medium Enterprise EBP             20
MED - SME Loans - Medium Scale Enterprise        12300
MIC - Microfinance Loans                          3515
SBA - SME Loans - Small Enterprise CLBA OS          20
SMA - SME Loans - Small Scale Enterprise         12032
Name: Sum of Sum of Loan Portfolio, dtype: int64

In [22]:
df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    ['AGRICULTURAL LOANS -AGRA','AGRICULTURAL LOANS -AGRI','AIC - Agrarian Reform & Other Agri Loans - AI'],
    'Agricultural Loans')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    ['IBK - Interbank Term Loans Recble - KB/UKB','IBO - Interbank Term Loans Recble - Oth Banks','INB - Interbank Term Loans Recble - NBQB'],
    'Interbank Term Loans Receivable')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    'GNF - Loans to GOCC Non-Financial',
    'Loans to GOCC')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    ['GLC - Loans to LGU - Cust Liab under TR','LLG - Loans to Local Govt Unit'],
    'Loans to LGU')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    'LNG - Loans to National Govt',
    'Loans to National Government')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    ['BA - Loans to Priv Corp - Non Fin CL BA O/S','CLT - Loans to Priv Corp -Non Fin CL under TR','LPN - Loans to Private Corp. - Non Financial'],
    'Loans to Private Corp - Non Financial')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    'LPF - Loans to Private Corp. - Financial',
    'Loans to Private Corp - Financial')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    ['MEB - SME Loans - Medium Enterprise EBP','MED - SME Loans - Medium Scale Enterprise'],
    'SME Loans - Medium')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    ['SBA - SME Loans - Small Enterprise CLBA OS','SMA - SME Loans - Small Scale Enterprise'],
    'SME Loans - Small')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    'MIC - Microfinance Loans',
    'Microfinance Loans')

df2['Account/Loan Type'] = df2['Account/Loan Type'].replace(
    'IHP - Loans to Indl for Housing Purposes',
    'Loans to Individual')
    
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio,Month Name,Interest Rate Range
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00,DEC,10.00% - 11.99%
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,DEC,8.00% - 9.99%
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,SEPT,8.00% - 9.99%
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00,JUN,10.00% - 11.99%
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00,MAR,10.00% - 11.99%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92,JUN,5.00% - 7.99%
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06,MAR,5.00% - 7.99%
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22,SEPT,5.00% - 7.99%
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36,JUN,5.00% - 7.99%
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50,MAR,5.00% - 7.99%

In [23]:
Region_grouped = df2.groupby('Region')['BORROWER_CODE_NAME'].count()
Region_grouped

Region
Administrative Region of Muslim Mindanao     438
Autonomous Region in Muslim Mindanao          58
Bicol                                       3235
Cagayan Valley                              4538
Calabarzon                                  4327
Caraga                                      3146
Central Luzon                               4111
Central Visayas                             3671
Cordillera Administrative Region             848
Cordillera Autonomous Region                  11
Davao                                       3615
Eastern Visayas                             2944
Ilocos                                       985
MIMAROPA                                    1293
National Capital Region                     6724
Northern Mindanao                           4032
Soccsksargen                                3031
Western Visayas                             3832
Zamboanga Peninsula                         1746
Name: BORROWER_CODE_NAME, dtype: int64

In [24]:
df2['Region'] = df2['Region'].replace(
    ['Administrative Region of Muslim Mindanao','Autonomous Region in Muslim Mindanao'],
    'Bangsamoro Autonomous Region In Muslim Mindanao')

df2['Region'] = df2['Region'].replace(
    'Cordillera Autonomous Region',
    'Cordillera Administrative Region')

In [25]:
df2.groupby('Region')['BORROWER_CODE_NAME'].count()

Region
Bangsamoro Autonomous Region In Muslim Mindanao     496
Bicol                                              3235
Cagayan Valley                                     4538
Calabarzon                                         4327
Caraga                                             3146
Central Luzon                                      4111
Central Visayas                                    3671
Cordillera Administrative Region                    859
Davao                                              3615
Eastern Visayas                                    2944
Ilocos                                              985
MIMAROPA                                           1293
National Capital Region                            6724
Northern Mindanao                                  4032
Soccsksargen                                       3031
Western Visayas                                    3832
Zamboanga Peninsula                                1746
Name: BORROWER_CODE_NAME, dtype: int64

In [26]:
df2.groupby('Account/Loan Type')['BORROWER_CODE_NAME'].count()

Account/Loan Type
Agricultural Loans                         851
Interbank Term Loans Receivable             22
Loans to GOCC                             1183
Loans to Individual                        437
Loans to LGU                              8742
Loans to National Government                42
Loans to Private Corp - Financial          437
Loans to Private Corp - Non Financial    12984
Microfinance Loans                        3515
SME Loans - Medium                       12320
SME Loans - Small                        12052
Name: BORROWER_CODE_NAME, dtype: int64

In [27]:
df2

,YEAR,MONTH_ID,BORROWER_CODE_NAME,JOINT,LENDING UNIT,LG,Major Industry,Account/Loan Type,Customer Size,Development Lending Program,Location,Region,Account Class,Interest Rate,Interest Type,Type of Facility,Collateral Type,Collateral Type Description,Source,Loan Term,No. of Days-Loan Term,Past Due Date,Loan Status,Area Code,Sum of Sum of Approved Amount,Sum of Sum of Collateral Amount,Sum of Sum of Release Amount,Sum of Sum of Booked Reserves,Sum of Sum of Loan Portfolio,Month Name,Interest Rate Range
0,2019,12,BORROWER_1,BORROWER_1-2019-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,49000000.0,0.0,7000000.00,0.0,7000000.00,DEC,10.00% - 11.99%
9462,2020,12,BORROWER_1,BORROWER_1-2020-12,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,DEC,8.00% - 9.99%
7078,2020,9,BORROWER_1,BORROWER_1-2020-9,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,9.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,60000000.0,0.0,10000000.00,0.0,10000000.00,SEPT,8.00% - 9.99%
4718,2020,6,BORROWER_1,BORROWER_1-2020-6,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,120,NaT,CUR,PA,57000000.0,0.0,9000000.00,0.0,9000000.00,JUN,10.00% - 11.99%
2370,2020,3,BORROWER_1,BORROWER_1-2020-3,SME (NCR) DEPARTMENT,SMERMMLG,WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VE...,SME Loans - Small,Small,MSME CENTER SEED,METRO MANILA,National Capital Region,CURRENT,10.0,Variable,REVOLVING CREDIT LINE,Unsecured,(blank),DBP,Short Term,119,NaT,CUR,PA,56000000.0,0.0,7000000.00,0.0,7000000.00,MAR,10.00% - 11.99%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36353,2023,6,BORROWER_999,BORROWER_999-2023-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,11693892.92,JUN,5.00% - 7.99%
33946,2023,3,BORROWER_999,BORROWER_999-2023-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,13642875.06,MAR,5.00% - 7.99%
48042,2024,9,BORROWER_999,BORROWER_999-2024-9,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,1948982.22,SEPT,5.00% - 7.99%
45755,2024,6,BORROWER_999,BORROWER_999-2024-6,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,3897964.36,JUN,5.00% - 7.99%
43437,2024,3,BORROWER_999,BORROWER_999-2024-3,CAGAYAN DE ORO LENDING CENTER,NMLG,PUBLIC ADMINISTRATION AND DEFENSE; COMPULSORY ...,Loans to LGU,Micro,Agri Compliance,MISAMIS ORIENTAL,Northern Mindanao,PASS,7.4,Variable,TERM LOAN,Unsecured,(blank),DBP,Long Term,2010,NaT,CUR,PA,53973000.0,0.0,42877607.16,0.0,5846946.50,MAR,5.00% - 7.99%

In [28]:
df2.to_excel('cleaned_dataset.xlsx')

PermissionError: [Errno 13] Permission denied: 'cleaned_dataset.xlsx'